name: Build docu for tag

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-docu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build pdf docu
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-fonts-recommended texlive-fonts-extra texlive-luatex
          bash -x ${GITHUB_WORKSPACE}/docs/build_pdf.sh -o EBcL_SDK_$GITHUB_REF_NAME.pdf
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/docs/EBcL_SDK_$GITHUB_REF_NAME.pdf
          asset_name: EBcL_SDK_$GITHUB_REF_NAME.pdf
          asset_content_type: application/pdf
